{
 "title": "MJS",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "jobmanager",
    "label": "Job Manager",
    "query": {
     "query": "label_values(up{job=\"mjs\"},instance)"
    }
   },
   { "name": "user", "label": "User", "query": { "query": "label_values(mjs_users,user)" } },
   { "name": "top", "query": "1,2,3,4,5,6,7,8" }
  ]
 },
 "panels": [
  { "title": "Get Started", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "options": {
    "content": "# Dashboard Overview\n\nThis dashboard provides live cluster monitoring and alerts for your MJS cluster.\n\n## Rows\n\nInformation is organized into collapsible rows.  Each row has a title that describes the type or purpose of the information contained in the row. This should make it quick and easy to navigate to the information relevant to you.\n\n## Visualizations\n\nWithin each row is a collection of visualizations. These visualizations show information about the cluster in one of the following ways:\n - over a period of time (controlled by Grafana's *time picker* in the top right of the dashboard)\n - at one instant of time (corresponding to the *end* of the selected time period)\n - right now (alerts only)\n\nYou can see the time associated with each visualization by hovering over the `ⓘ` icon near the title.\n\n## Users\n\nSome visualizations can be configured to display information for a subset of cluster users.  You can identify these visualizations by looking for an `[All]` tag in their title. To change the subset of users displayed, click the `User` dropdown in the top left of the dashboard and select one or more users.  The visualizations should automatically update to reflect the subset of users selected."
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "options": {
    "content": "# Data & Metrics\n\nHere is a description of each section of the dashboard and the information contained within it.\n\n## Alerts\n\nReal-time issues affecting the operation of a cluster.  Alerts are categorized as follows:\n- High severity: You should take immediate action (e.g. the cluster is unusable for one or more users)\n- Medium severity: You probably need to take action soon (e.g. the cluster might become unusable otherwise)\n- Low severity: You do not need to take action but doing so can improve the operation of the cluster\n\nEach alert can be expanded to see a more detailed explanation of its importance and the conditions that triggered it.  Where possible, alerts suggest other visualizations in the dashboard that can assist further investigation.\n\n## Summary\n\nA high-level summary of cluster statistics from the more detailed sections below. You can use this section together with the Alerts section to get a quick overview of the cluster's health *right now*, including whether the cluster is up, how many workers and jobs it has, who is using it, and how much disk space and network traffic it is using.\n\n## Usage\n\nInformation about the overall cluster utilization (including license usage) by users over time. Most information about jobs and tasks is contained in this section, including the number of jobs and tasks by state, their queue times, their running durations, and when they were created, submitted, started, and finished.\n\n## Auditing\n\nRecords of the cumulative cluster time spent for the time period selected in Grafana, broken down by user, MATLAB version, and job type.  This information can be useful for auditing purposes like seeing how much the cluster is being used, retrospective billing by user or group, and determining which versions of MATLAB and/or job types are actually being used.\n\n## Process\n\nInformation about the uptime, number of restarts, and memory consumption of the job manager process.\n\n## Scheduler\n\nDetailed information about the core scheduling components of the job manager, including the worker pool, job queue, scheduler, and task dispatcher.  Most of the information of this section is primarily useful for diagnosing cluster issues but can also be used to gain insights into whether the cluster is operating smoothly and efficiently.\n\n## Storage\n\nInformation about how much disk space and disk activity the job manager is using and generating, respectively. Disk usage can be broken down by user and data type for diagnosing excessive usage while tracking of the low-level database operations and cache can be used to detect strange usage patterns or performance issues.\n\n## Communication\n\nInformation about data transfer to/from the job manager and the number and type of incoming/outgoing network calls. Data transfer rates and the number of network calls can give a sense of how much load the job manager is putting on the network while the low-level network calls being made can highlight strange usage patterns or performance issues.\n\n## Security\n\nInformation about the security settings of the job manager and user activity associated with sensitive cluster operations that require authentication and authorization."
   },
   "targets": [
    {}
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "High Severity",
   "type": "alertlist",
   "description": "As of ${__to:date:YYYY-MM-DD HH:mm:ss}",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 }
  },
  {
   "title": "Medium Severity",
   "type": "alertlist",
   "description": "As of ${__to:date:YYYY-MM-DD HH:mm:ss}",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 }
  },
  {
   "title": "Low Severity",
   "type": "alertlist",
   "description": "As of ${__to:date:YYYY-MM-DD HH:mm:ss}",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 }
  },
  {
   "title": "Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status",
     "type": "stat",
     "description": "As of ${__to:date:YYYY-MM-DD HH:mm:ss}",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Cluster Utilization",
     "type": "gauge",
     "description": "As of ${__to:date:YYYY-MM-DD HH:mm:ss}",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "((sum(mjs_worker_state_transitions_total{instance=~\"$jobmanager\",to=\"busy\"}) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})) - (sum(mjs_worker_state_transitions_total{instance=~\"$jobmanager\",from=\"busy\"}) or 0 * sum(mjs_up{instance=~\"$jobmanager\"}))) / clamp_min((sum(mjs_workers{instance=~\"$jobmanager\", type=\"max\"})) or (((sum(mjs_worker_state_transitions_total{instance=~\"$jobmanager\",to=~\"busy|idle\"}) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})) - (sum(mjs_worker_state_transitions_total{instance=~\"$jobmanager\",from=~\"busy|idle\"}) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})))), 1)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Workers",
     "type": "barchart",
     "description": "As of ${__to:date:YYYY-MM-DD HH:mm:ss}",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(sum(mjs_worker_state_transitions_total{instance=~\"$jobmanager\",to=\"busy\"}) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})) - (sum(mjs_worker_state_transitions_total{instance=~\"$jobmanager\",from=\"busy\"}) or 0 * sum(mjs_up{instance=~\"$jobmanager\"}))",
       "legendFormat": "busy"
      },
      {
       "expr": "(sum(mjs_worker_state_transitions_total{instance=~\"$jobmanager\",to=\"idle\"}) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})) - (sum(mjs_worker_state_transitions_total{instance=~\"$jobmanager\",from=\"idle\"}) or 0 * sum(mjs_up{instance=~\"$jobmanager\"}))",
       "legendFormat": "idle"
      },
      {
       "expr": "clamp_min(sum(mjs_workers{instance=~\"$jobmanager\",type=\"max\"}) - ((sum(mjs_worker_state_transitions_total{instance=~\"$jobmanager\",to=~\"busy|idle\"}) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})) - (sum(mjs_worker_state_transitions_total{instance=~\"$jobmanager\",from=~\"busy|idle\"}) or 0 * sum(mjs_up{instance=~\"$jobmanager\"}))), 0)",
       "legendFormat": "pending"
      }
     ]
    },
    {
     "title": "Jobs [$user]",
     "type": "barchart",
     "description": "As of ${__to:date:YYYY-MM-DD HH:mm:ss}",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(sum(mjs_work_unit_state_transitions_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",to=\"pending\"}) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})) - (sum(mjs_work_unit_state_transitions_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",from=\"pending\"}) or 0 * sum(mjs_up{instance=~\"$jobmanager\"}))",
       "legendFormat": "pending"
      },
      {
       "expr": "(sum(mjs_work_unit_state_transitions_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",to=\"queued\"}) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})) - (sum(mjs_work_unit_state_transitions_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",from=\"queued\"}) or 0 * sum(mjs_up{instance=~\"$jobmanager\"}))",
       "legendFormat": "queued"
      },
      {
       "expr": "(sum(mjs_work_unit_state_transitions_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",to=\"running\"}) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})) - (sum(mjs_work_unit_state_transitions_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",from=\"running\"}) or 0 * sum(mjs_up{instance=~\"$jobmanager\"}))",
       "legendFormat": "running"
      },
      {
       "expr": "(sum(mjs_work_unit_state_transitions_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",to=\"finished\"}) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})) - (sum(mjs_work_unit_state_transitions_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",from=\"finished\"}) or 0 * sum(mjs_up{instance=~\"$jobmanager\"}))",
       "legendFormat": "finished"
      }
     ]
    },
    {
     "title": "Licenses in Use [$user]",
     "type": "barchart",
     "description": "As of ${__to:date:YYYY-MM-DD HH:mm:ss}",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "topk($top, clamp_max(sum by (user) (mjs_matlab_processes{instance=~\"$jobmanager\",user=~\"$user\"}) > 0, 200))\nor (-1 * absent(topk($top, clamp_max(sum by (user) (mjs_matlab_processes{instance=~\"$jobmanager\",user=~\"$user\"}) > 0, 200))) and sum(mjs_up{instance=~\"$jobmanager\"}))",
       "legendFormat": "{{user}}"
      },
      {
       "expr": "sum(clamp_max(sum by (user) (mjs_matlab_processes{instance=~\"$jobmanager\",user=~\"$user\"}) > 0, 200) unless topk($top, clamp_max(sum by (user) (mjs_matlab_processes{instance=~\"$jobmanager\",user=~\"$user\"}) > 0, 200))) > 0",
       "legendFormat": "other"
      }
     ]
    },
    {
     "title": "Job Manager Disk Usage",
     "type": "gauge",
     "description": "As of ${__to:date:YYYY-MM-DD HH:mm:ss}",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (type) (mjs_storage{instance=~\"$jobmanager\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "User Data [$user]",
     "type": "barchart",
     "description": "As of ${__to:date:YYYY-MM-DD HH:mm:ss}",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "# NOTE: Filter out users with 0 bytes used\ntopk($top, sum by (user) (mjs_work_unit_data{instance=~\"$jobmanager\",user=~\"$user\"}) > 0) or (-1 * absent(topk($top, sum by (user) (mjs_work_unit_data{instance=~\"$jobmanager\",user=~\"$user\"}) > 0)) and sum(mjs_up{instance=~\"$jobmanager\"}))",
       "legendFormat": "{{user}}"
      },
      {
       "expr": "sum(sum by (user) (mjs_work_unit_data{instance=~\"$jobmanager\",user=~\"$user\"}) > 0 unless topk($top, sum by (user) (mjs_work_unit_data{instance=~\"$jobmanager\",user=~\"$user\"}) > 0)) > 0",
       "legendFormat": "other"
      }
     ]
    },
    {
     "title": "Upload",
     "type": "stat",
     "description": "As of ${__to:date:YYYY-MM-DD HH:mm:ss}",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "round(sum(rate(mjs_data_transfer_total{instance=~\"$jobmanager\",type=\"upload\"}[$__rate_interval]))) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "upload"
      }
     ]
    },
    {
     "title": "Download",
     "type": "stat",
     "description": "As of ${__to:date:YYYY-MM-DD HH:mm:ss}",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "round(sum(rate(mjs_data_transfer_total{instance=~\"$jobmanager\",type=\"download\"}[$__rate_interval]))) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "download"
      }
     ]
    }
   ]
  },
  {
   "title": "Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster Utilization",
     "type": "timeseries",
     "description": "Over period [${__from:date:YYYY-MM-DD HH:mm:ss} to ${__to:date:YYYY-MM-DD HH:mm:ss}]",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(sum(mjs_worker_state_transitions_total{instance=~\"$jobmanager\",to=\"busy\"}) - sum(mjs_worker_state_transitions_total{instance=~\"$jobmanager\",from=\"busy\"})) / clamp_min((sum(mjs_workers{instance=~\"$jobmanager\", type=\"max\"})) or ((sum(mjs_worker_state_transitions_total{instance=~\"$jobmanager\",to=~\"busy|idle\"}) - sum(mjs_worker_state_transitions_total{instance=~\"$jobmanager\",from=~\"busy|idle\"}))), 1) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "utilization"
      }
     ]
    },
    {
     "title": "Throughput [$user]",
     "type": "timeseries",
     "description": "Over period [${__from:date:YYYY-MM-DD HH:mm:ss} to ${__to:date:YYYY-MM-DD HH:mm:ss}]",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(mjs_work_unit_state_transitions_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",to=\"finished\"}[$__rate_interval])) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "job"
      },
      {
       "expr": "sum(rate(mjs_work_unit_state_transitions_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",to=\"finished\"}[$__rate_interval])) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "task"
      }
     ]
    },
    {
     "title": "Licenses in Use [$user]",
     "type": "timeseries",
     "description": "Over period [${__from:date:YYYY-MM-DD HH:mm:ss} to ${__to:date:YYYY-MM-DD HH:mm:ss}]",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "# NOTE: Include any users that have checked out a license since the job manager started (up to that point in time) so that they don't first appear non-zero the first time they use a license. However, we still filter the user out if they are all 0 license use over the range\nclamp_max(sum by (user) (mjs_matlab_processes{instance=~\"$jobmanager\",user=~\"$user\"}), 200) or 0 * sum by (user) (mjs_users{instance=~\"$jobmanager\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "License Failures [$user]",
     "type": "timeseries",
     "description": "Over period [${__from:date:YYYY-MM-DD HH:mm:ss} to ${__to:date:YYYY-MM-DD HH:mm:ss}]",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (user) ((1 * mjs_license_errors_total{instance=~\"$jobmanager\",user=~\"$user\"} or 0 * mjs_license_errors_total{instance=~\"$jobmanager\",user=~\"$user\"} offset $__interval + last_over_time(mjs_license_errors_total{instance=~\"$jobmanager\",user=~\"$user\"}[999d])) - (1 * mjs_license_errors_total{instance=~\"$jobmanager\",user=~\"$user\"} offset $__interval or 0 * mjs_license_errors_total{instance=~\"$jobmanager\",user=~\"$user\"}) or last_over_time(mjs_license_errors_total{instance=~\"$jobmanager\",user=~\"$user\"}[999d]) unless last_over_time(mjs_license_errors_total{instance=~\"$jobmanager\",user=~\"$user\"}[999d] offset $__interval)) or 0 * sum by (user) (mjs_users{instance=~\"$jobmanager\"})",
       "legendFormat": "{{user}}"
      },
      {
       "expr": "0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "Jobs [$user]",
     "type": "timeseries",
     "description": "Over period [${__from:date:YYYY-MM-DD HH:mm:ss} to ${__to:date:YYYY-MM-DD HH:mm:ss}]",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(sum(mjs_work_unit_state_transitions_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",to=\"pending\"}) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})) - (sum(mjs_work_unit_state_transitions_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",from=\"pending\"}) or 0 * sum(mjs_up{instance=~\"$jobmanager\"}))",
       "legendFormat": "pending"
      },
      {
       "expr": "(sum(mjs_work_unit_state_transitions_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",to=\"queued\"}) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})) - (sum(mjs_work_unit_state_transitions_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",from=\"queued\"}) or 0 * sum(mjs_up{instance=~\"$jobmanager\"}))",
       "legendFormat": "queued"
      },
      {
       "expr": "(sum(mjs_work_unit_state_transitions_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",to=\"running\"}) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})) - (sum(mjs_work_unit_state_transitions_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",from=\"running\"}) or 0 * sum(mjs_up{instance=~\"$jobmanager\"}))",
       "legendFormat": "running"
      },
      {
       "expr": "(sum(mjs_work_unit_state_transitions_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",to=\"finished\"}) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})) - (sum(mjs_work_unit_state_transitions_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",from=\"finished\"}) or 0 * sum(mjs_up{instance=~\"$jobmanager\"}))",
       "legendFormat": "finished"
      }
     ]
    },
    {
     "title": "Tasks [$user]",
     "type": "timeseries",
     "description": "Over period [${__from:date:YYYY-MM-DD HH:mm:ss} to ${__to:date:YYYY-MM-DD HH:mm:ss}]",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(sum(mjs_work_unit_state_transitions_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",to=\"pending\"}) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})) - (sum(mjs_work_unit_state_transitions_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",from=\"pending\"}) or 0 * sum(mjs_up{instance=~\"$jobmanager\"}))",
       "legendFormat": "pending"
      },
      {
       "expr": "(sum(mjs_work_unit_state_transitions_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",to=\"queued\"}) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})) - (sum(mjs_work_unit_state_transitions_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",from=\"queued\"}) or 0 * sum(mjs_up{instance=~\"$jobmanager\"}))",
       "legendFormat": "queued"
      },
      {
       "expr": "(sum(mjs_work_unit_state_transitions_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",to=\"running\"}) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})) - (sum(mjs_work_unit_state_transitions_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",from=\"running\"}) or 0 * sum(mjs_up{instance=~\"$jobmanager\"}))",
       "legendFormat": "running"
      },
      {
       "expr": "(sum(mjs_work_unit_state_transitions_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",to=\"finished\"}) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})) - (sum(mjs_work_unit_state_transitions_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",from=\"finished\"}) or 0 * sum(mjs_up{instance=~\"$jobmanager\"}))",
       "legendFormat": "finished"
      }
     ]
    },
    {
     "title": "Job Queue Times [$user]",
     "type": "bargauge",
     "description": "For period [${__from:date:YYYY-MM-DD HH:mm:ss} to ${__to:date:YYYY-MM-DD HH:mm:ss}]",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
     "targets": [
      {
       "expr": "sum by (le) (1 * mjs_work_unit_queue_times_bucket{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\"} @ ${__to:date:seconds} or 1 * last_over_time(mjs_work_unit_queue_times_bucket{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\"}[999d] @ ${__to:date:seconds})) - sum by (le) (1 * mjs_work_unit_queue_times_bucket{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\"} @ ${__from:date:seconds} or 1 * last_over_time(mjs_work_unit_queue_times_bucket{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\"}[999d] @ ${__from:date:seconds}) or 0 * last_over_time(mjs_work_unit_queue_times_bucket{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\"}[999d]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Task Queue Times [$user]",
     "type": "bargauge",
     "description": "For period [${__from:date:YYYY-MM-DD HH:mm:ss} to ${__to:date:YYYY-MM-DD HH:mm:ss}]",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
     "targets": [
      {
       "expr": "sum by (le) (1 * mjs_work_unit_queue_times_bucket{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\"} @ ${__to:date:seconds} or 1 * last_over_time(mjs_work_unit_queue_times_bucket{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\"}[999d] @ ${__to:date:seconds})) - sum by (le) (1 * mjs_work_unit_queue_times_bucket{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\"} @ ${__from:date:seconds} or 1 * last_over_time(mjs_work_unit_queue_times_bucket{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\"}[999d] @ ${__from:date:seconds}) or 0 * last_over_time(mjs_work_unit_queue_times_bucket{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\"}[999d]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Job Running Durations [$user]",
     "type": "bargauge",
     "description": "For period [${__from:date:YYYY-MM-DD HH:mm:ss} to ${__to:date:YYYY-MM-DD HH:mm:ss}]",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
     "targets": [
      {
       "expr": "sum by (le) (1 * mjs_work_unit_durations_bucket{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\"} @ ${__to:date:seconds} or 1 * last_over_time(mjs_work_unit_durations_bucket{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\"}[999d] @ ${__to:date:seconds})) - sum by (le) (1 * mjs_work_unit_durations_bucket{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\"} @ ${__from:date:seconds} or 1 * last_over_time(mjs_work_unit_durations_bucket{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\"}[999d] @ ${__from:date:seconds}) or 0 * last_over_time(mjs_work_unit_durations_bucket{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\"}[999d]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Task Running Durations [$user]",
     "type": "bargauge",
     "description": "For period [${__from:date:YYYY-MM-DD HH:mm:ss} to ${__to:date:YYYY-MM-DD HH:mm:ss}]",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
     "targets": [
      {
       "expr": "sum by (le) (1 * mjs_work_unit_durations_bucket{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\"} @ ${__to:date:seconds} or 1 * last_over_time(mjs_work_unit_durations_bucket{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\"}[999d] @ ${__to:date:seconds})) - sum by (le) (1 * mjs_work_unit_durations_bucket{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\"} @ ${__from:date:seconds} or 1 * last_over_time(mjs_work_unit_durations_bucket{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\"}[999d] @ ${__from:date:seconds}) or 0 * last_over_time(mjs_work_unit_durations_bucket{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\"}[999d]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Job Events [$user]",
     "type": "timeseries",
     "description": "Over period [${__from:date:YYYY-MM-DD HH:mm:ss} to ${__to:date:YYYY-MM-DD HH:mm:ss}]",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum((1 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",event=\"created\"} or 0 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",event=\"created\"} offset $__interval + last_over_time(mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",event=\"created\"}[999d])) - (1 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",event=\"created\"} offset $__interval or 0 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",event=\"created\"}) or last_over_time(mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",event=\"created\"}[999d]) unless last_over_time(mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",event=\"created\"}[999d] offset $__interval)) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "created"
      },
      {
       "expr": "sum((1 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",event=\"submitted\"} or 0 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",event=\"submitted\"} offset $__interval + last_over_time(mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",event=\"submitted\"}[999d])) - (1 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",event=\"submitted\"} offset $__interval or 0 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",event=\"submitted\"}) or last_over_time(mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",event=\"submitted\"}[999d]) unless last_over_time(mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",event=\"submitted\"}[999d] offset $__interval)) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "submitted"
      },
      {
       "expr": "sum((1 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",event=\"started\"} or 0 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",event=\"started\"} offset $__interval + last_over_time(mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",event=\"started\"}[999d])) - (1 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",event=\"started\"} offset $__interval or 0 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",event=\"started\"}) or last_over_time(mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",event=\"started\"}[999d]) unless last_over_time(mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",event=\"started\"}[999d] offset $__interval)) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "started"
      },
      {
       "expr": "sum((1 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",event=\"finished\"} or 0 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",event=\"finished\"} offset $__interval + last_over_time(mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",event=\"finished\"}[999d])) - (1 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",event=\"finished\"} offset $__interval or 0 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",event=\"finished\"}) or last_over_time(mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",event=\"finished\"}[999d]) unless last_over_time(mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",event=\"finished\"}[999d] offset $__interval)) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "finished"
      },
      {
       "expr": "sum((1 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",event=\"errored\"} or 0 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",event=\"errored\"} offset $__interval + last_over_time(mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",event=\"errored\"}[999d])) - (1 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",event=\"errored\"} offset $__interval or 0 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",event=\"errored\"}) or last_over_time(mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",event=\"errored\"}[999d]) unless last_over_time(mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",event=\"errored\"}[999d] offset $__interval)) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "errored"
      },
      {
       "expr": "sum((1 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",event=\"canceled\"} or 0 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",event=\"canceled\"} offset $__interval + last_over_time(mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",event=\"canceled\"}[999d])) - (1 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",event=\"canceled\"} offset $__interval or 0 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",event=\"canceled\"}) or last_over_time(mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",event=\"canceled\"}[999d]) unless last_over_time(mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",event=\"canceled\"}[999d] offset $__interval)) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "canceled"
      },
      {
       "expr": "sum((1 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",event=\"failed\"} or 0 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",event=\"failed\"} offset $__interval + last_over_time(mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",event=\"failed\"}[999d])) - (1 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",event=\"failed\"} offset $__interval or 0 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",event=\"failed\"}) or last_over_time(mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",event=\"failed\"}[999d]) unless last_over_time(mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",event=\"failed\"}[999d] offset $__interval)) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "failed"
      },
      {
       "expr": "sum((1 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",event=\"restarted\"} or 0 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",event=\"restarted\"} offset $__interval + last_over_time(mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",event=\"restarted\"}[999d])) - (1 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",event=\"restarted\"} offset $__interval or 0 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",event=\"restarted\"}) or last_over_time(mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",event=\"restarted\"}[999d]) unless last_over_time(mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",event=\"restarted\"}[999d] offset $__interval)) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "restarted"
      },
      {
       "expr": "sum((1 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",event=\"deleted\"} or 0 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",event=\"deleted\"} offset $__interval + last_over_time(mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",event=\"deleted\"}[999d])) - (1 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",event=\"deleted\"} offset $__interval or 0 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",event=\"deleted\"}) or last_over_time(mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",event=\"deleted\"}[999d]) unless last_over_time(mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"job\",event=\"deleted\"}[999d] offset $__interval)) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "deleted"
      },
      {
       "expr": "0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "Task Events [$user]",
     "type": "timeseries",
     "description": "Over period [${__from:date:YYYY-MM-DD HH:mm:ss} to ${__to:date:YYYY-MM-DD HH:mm:ss}]",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum((1 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",event=\"created\"} or 0 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",event=\"created\"} offset $__interval + last_over_time(mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",event=\"created\"}[999d])) - (1 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",event=\"created\"} offset $__interval or 0 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",event=\"created\"}) or last_over_time(mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",event=\"created\"}[999d]) unless last_over_time(mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",event=\"created\"}[999d] offset $__interval)) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "created"
      },
      {
       "expr": "sum((1 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",event=\"submitted\"} or 0 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",event=\"submitted\"} offset $__interval + last_over_time(mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",event=\"submitted\"}[999d])) - (1 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",event=\"submitted\"} offset $__interval or 0 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",event=\"submitted\"}) or last_over_time(mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",event=\"submitted\"}[999d]) unless last_over_time(mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",event=\"submitted\"}[999d] offset $__interval)) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "submitted"
      },
      {
       "expr": "sum((1 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",event=\"started\"} or 0 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",event=\"started\"} offset $__interval + last_over_time(mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",event=\"started\"}[999d])) - (1 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",event=\"started\"} offset $__interval or 0 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",event=\"started\"}) or last_over_time(mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",event=\"started\"}[999d]) unless last_over_time(mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",event=\"started\"}[999d] offset $__interval)) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "started"
      },
      {
       "expr": "sum((1 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",event=\"finished\"} or 0 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",event=\"finished\"} offset $__interval + last_over_time(mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",event=\"finished\"}[999d])) - (1 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",event=\"finished\"} offset $__interval or 0 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",event=\"finished\"}) or last_over_time(mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",event=\"finished\"}[999d]) unless last_over_time(mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",event=\"finished\"}[999d] offset $__interval)) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "finished"
      },
      {
       "expr": "sum((1 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",event=\"errored\"} or 0 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",event=\"errored\"} offset $__interval + last_over_time(mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",event=\"errored\"}[999d])) - (1 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",event=\"errored\"} offset $__interval or 0 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",event=\"errored\"}) or last_over_time(mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",event=\"errored\"}[999d]) unless last_over_time(mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",event=\"errored\"}[999d] offset $__interval)) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "errored"
      },
      {
       "expr": "sum((1 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",event=\"canceled\"} or 0 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",event=\"canceled\"} offset $__interval + last_over_time(mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",event=\"canceled\"}[999d])) - (1 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",event=\"canceled\"} offset $__interval or 0 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",event=\"canceled\"}) or last_over_time(mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",event=\"canceled\"}[999d]) unless last_over_time(mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",event=\"canceled\"}[999d] offset $__interval)) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "canceled"
      },
      {
       "expr": "sum((1 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",event=\"failed\"} or 0 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",event=\"failed\"} offset $__interval + last_over_time(mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",event=\"failed\"}[999d])) - (1 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",event=\"failed\"} offset $__interval or 0 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",event=\"failed\"}) or last_over_time(mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",event=\"failed\"}[999d]) unless last_over_time(mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",event=\"failed\"}[999d] offset $__interval)) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "failed"
      },
      {
       "expr": "sum((1 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",event=\"restarted\"} or 0 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",event=\"restarted\"} offset $__interval + last_over_time(mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",event=\"restarted\"}[999d])) - (1 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",event=\"restarted\"} offset $__interval or 0 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",event=\"restarted\"}) or last_over_time(mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",event=\"restarted\"}[999d]) unless last_over_time(mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",event=\"restarted\"}[999d] offset $__interval)) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "restarted"
      },
      {
       "expr": "sum((1 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",event=\"deleted\"} or 0 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",event=\"deleted\"} offset $__interval + last_over_time(mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",event=\"deleted\"}[999d])) - (1 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",event=\"deleted\"} offset $__interval or 0 * mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",event=\"deleted\"}) or last_over_time(mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",event=\"deleted\"}[999d]) unless last_over_time(mjs_work_unit_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"task\",event=\"deleted\"}[999d] offset $__interval)) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "deleted"
      },
      {
       "expr": "0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": " "
      }
     ]
    }
   ]
  },
  {
   "title": "Auditing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top Users [$user]",
     "type": "barchart",
     "description": "For period [${__from:date:YYYY-MM-DD HH:mm:ss} to ${__to:date:YYYY-MM-DD HH:mm:ss}]",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk($top, round(sum by (user) ((1 * mjs_job_history_times_total{instance=~\"$jobmanager\",user=~\"$user\"} @ ${__to:date:seconds} or 1 * last_over_time(mjs_job_history_times_total{instance=~\"$jobmanager\",user=~\"$user\"}[999d] @ ${__to:date:seconds})) - (1 * mjs_job_history_times_total{instance=~\"$jobmanager\",user=~\"$user\"} @ ${__from:date:seconds} or 1 * last_over_time(mjs_job_history_times_total{instance=~\"$jobmanager\",user=~\"$user\"}[999d] @ ${__from:date:seconds}) or 0 * last_over_time(mjs_job_history_times_total{instance=~\"$jobmanager\",user=~\"$user\"}[999d])))) > 0)\nor (-1 * absent(topk($top, round(sum by (user) ((1 * mjs_job_history_times_total{instance=~\"$jobmanager\",user=~\"$user\"} @ ${__to:date:seconds} or 1 * last_over_time(mjs_job_history_times_total{instance=~\"$jobmanager\",user=~\"$user\"}[999d] @ ${__to:date:seconds})) - (1 * mjs_job_history_times_total{instance=~\"$jobmanager\",user=~\"$user\"} @ ${__from:date:seconds} or 1 * last_over_time(mjs_job_history_times_total{instance=~\"$jobmanager\",user=~\"$user\"}[999d] @ ${__from:date:seconds}) or 0 * last_over_time(mjs_job_history_times_total{instance=~\"$jobmanager\",user=~\"$user\"}[999d])))) > 0)) and sum(mjs_up{instance=~\"$jobmanager\"}))",
       "legendFormat": "{{user}}"
      },
      {
       "expr": "round(sum(round(sum by (user) ((1 * mjs_job_history_times_total{instance=~\"$jobmanager\",user=~\"$user\"} @ ${__to:date:seconds} or 1 * last_over_time(mjs_job_history_times_total{instance=~\"$jobmanager\",user=~\"$user\"}[999d] @ ${__to:date:seconds})) - (1 * mjs_job_history_times_total{instance=~\"$jobmanager\",user=~\"$user\"} @ ${__from:date:seconds} or 1 * last_over_time(mjs_job_history_times_total{instance=~\"$jobmanager\",user=~\"$user\"}[999d] @ ${__from:date:seconds}) or 0 * last_over_time(mjs_job_history_times_total{instance=~\"$jobmanager\",user=~\"$user\"}[999d])))) > 0 unless topk($top, round(sum by (user) ((1 * mjs_job_history_times_total{instance=~\"$jobmanager\",user=~\"$user\"} @ ${__to:date:seconds} or 1 * last_over_time(mjs_job_history_times_total{instance=~\"$jobmanager\",user=~\"$user\"}[999d] @ ${__to:date:seconds})) - (1 * mjs_job_history_times_total{instance=~\"$jobmanager\",user=~\"$user\"} @ ${__from:date:seconds} or 1 * last_over_time(mjs_job_history_times_total{instance=~\"$jobmanager\",user=~\"$user\"}[999d] @ ${__from:date:seconds}) or 0 * last_over_time(mjs_job_history_times_total{instance=~\"$jobmanager\",user=~\"$user\"}[999d])))) > 0))) > 0",
       "legendFormat": "other"
      }
     ]
    },
    {
     "title": "MATLAB Version [$user]",
     "type": "piechart",
     "description": "For period [${__from:date:YYYY-MM-DD HH:mm:ss} to ${__to:date:YYYY-MM-DD HH:mm:ss}]",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "# NOTE: Also include 0 values for all currently supported versions if no data for them so that we can display them in the legend (only)\nround(sum by (version) ((1 * mjs_job_history_times_total{instance=~\"$jobmanager\", user=~\"$user\"} @ ${__to:date:seconds} or 1 * last_over_time(mjs_job_history_times_total{instance=~\"$jobmanager\", user=~\"$user\"}[999d] @ ${__to:date:seconds})) - (1 * mjs_job_history_times_total{instance=~\"$jobmanager\", user=~\"$user\"} @ ${__from:date:seconds} or 1 * last_over_time(mjs_job_history_times_total{instance=~\"$jobmanager\", user=~\"$user\"}[999d] @ ${__from:date:seconds}) or 0 * last_over_time(mjs_job_history_times_total{instance=~\"$jobmanager\", user=~\"$user\"}[999d])))) > 0 or 0 * sum by (version) (mjs_versions)",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "Job Type [$user]",
     "type": "piechart",
     "description": "For period [${__from:date:YYYY-MM-DD HH:mm:ss} to ${__to:date:YYYY-MM-DD HH:mm:ss}]",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "# NOTE: Also include 0 values for all job types if no data for them so that we can display them in the legend (only)\nround(sum((1 * mjs_job_history_times_total{instance=~\"$jobmanager\",user=~\"$user\",mode=\"batch\",type=\"independent\"} @ ${__to:date:seconds} or 1 * last_over_time(mjs_job_history_times_total{instance=~\"$jobmanager\",user=~\"$user\",mode=\"batch\",type=\"independent\"}[999d] @ ${__to:date:seconds})) - (1 * mjs_job_history_times_total{instance=~\"$jobmanager\",user=~\"$user\",mode=\"batch\",type=\"independent\"} @ ${__from:date:seconds} or 1 * last_over_time(mjs_job_history_times_total{instance=~\"$jobmanager\",user=~\"$user\",mode=\"batch\",type=\"independent\"}[999d] @ ${__from:date:seconds}) or 0 * last_over_time(mjs_job_history_times_total{instance=~\"$jobmanager\",user=~\"$user\",mode=\"batch\",type=\"independent\"}[999d])))) > 0 or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "independent"
      },
      {
       "expr": "# NOTE: Also include 0 values for all currently supported versions if no data for them so that we can display them in the legend (only)\nround(sum((1 * mjs_job_history_times_total{instance=~\"$jobmanager\",user=~\"$user\",mode=\"batch\",type=\"pool\"} @ ${__to:date:seconds} or 1 * last_over_time(mjs_job_history_times_total{instance=~\"$jobmanager\",user=~\"$user\",mode=\"batch\",type=\"pool\"}[999d] @ ${__to:date:seconds})) - (1 * mjs_job_history_times_total{instance=~\"$jobmanager\",user=~\"$user\",mode=\"batch\",type=\"pool\"} @ ${__from:date:seconds} or 1 * last_over_time(mjs_job_history_times_total{instance=~\"$jobmanager\",user=~\"$user\",mode=\"batch\",type=\"pool\"}[999d] @ ${__from:date:seconds}) or 0 * last_over_time(mjs_job_history_times_total{instance=~\"$jobmanager\",user=~\"$user\",mode=\"batch\",type=\"pool\"}[999d])))) > 0 or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "batch_pool"
      },
      {
       "expr": "# NOTE: Also include 0 values for all currently supported versions if no data for them so that we can display them in the legend (only)\nround(sum((1 * mjs_job_history_times_total{instance=~\"$jobmanager\",user=~\"$user\",mode=\"batch\",type=\"spmd\"} @ ${__to:date:seconds} or 1 * last_over_time(mjs_job_history_times_total{instance=~\"$jobmanager\",user=~\"$user\",mode=\"batch\",type=\"spmd\"}[999d] @ ${__to:date:seconds})) - (1 * mjs_job_history_times_total{instance=~\"$jobmanager\",user=~\"$user\",mode=\"batch\",type=\"spmd\"} @ ${__from:date:seconds} or 1 * last_over_time(mjs_job_history_times_total{instance=~\"$jobmanager\",user=~\"$user\",mode=\"batch\",type=\"spmd\"}[999d] @ ${__from:date:seconds}) or 0 * last_over_time(mjs_job_history_times_total{instance=~\"$jobmanager\",user=~\"$user\",mode=\"batch\",type=\"spmd\"}[999d])))) > 0 or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "spmd"
      },
      {
       "expr": "# NOTE: Also include 0 values for all currently supported versions if no data for them so that we can display them in the legend (only)\nround(sum((1 * mjs_job_history_times_total{instance=~\"$jobmanager\",user=~\"$user\",mode=\"interactive\",type=\"parpool\"} @ ${__to:date:seconds} or 1 * last_over_time(mjs_job_history_times_total{instance=~\"$jobmanager\",user=~\"$user\",mode=\"interactive\",type=\"parpool\"}[999d] @ ${__to:date:seconds})) - (1 * mjs_job_history_times_total{instance=~\"$jobmanager\",user=~\"$user\",mode=\"interactive\",type=\"parpool\"} @ ${__from:date:seconds} or 1 * last_over_time(mjs_job_history_times_total{instance=~\"$jobmanager\",user=~\"$user\",mode=\"interactive\",type=\"parpool\"}[999d] @ ${__from:date:seconds}) or 0 * last_over_time(mjs_job_history_times_total{instance=~\"$jobmanager\",user=~\"$user\",mode=\"interactive\",type=\"parpool\"}[999d])))) > 0 or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "parpool"
      }
     ]
    }
   ]
  },
  {
   "title": "Process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "% uptime for 5 min",
     "type": "stat",
     "description": "As of ${__to:date:YYYY-MM-DD HH:mm:ss}",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "avg_over_time(((sum(mjs_up{instance=~\"$jobmanager\"}) or 0 * sum(last_over_time(mjs_up[999d])))[5m:5s]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "% uptime for 1 hour",
     "type": "stat",
     "description": "As of ${__to:date:YYYY-MM-DD HH:mm:ss}",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "avg_over_time(((sum(mjs_up{instance=~\"$jobmanager\"}) or 0 * sum(last_over_time(mjs_up[999d])))[1h:5s]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "% uptime for 1 day",
     "type": "stat",
     "description": "As of ${__to:date:YYYY-MM-DD HH:mm:ss}",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "avg_over_time(((sum(mjs_up{instance=~\"$jobmanager\"}) or 0 * sum(last_over_time(mjs_up[999d])))[1d:1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "% uptime for 1 week",
     "type": "stat",
     "description": "As of ${__to:date:YYYY-MM-DD HH:mm:ss}",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "avg_over_time(((sum(mjs_up{instance=~\"$jobmanager\"}) or 0 * sum(last_over_time(mjs_up[999d])))[7d:10m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Job Manager Memory",
     "type": "timeseries",
     "description": "Over period [${__from:date:YYYY-MM-DD HH:mm:ss} to ${__to:date:YYYY-MM-DD HH:mm:ss}]",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(mjs_process_memory{type=\"max\", instance=~\"$jobmanager\"})",
       "legendFormat": "maximum"
      },
      {
       "expr": "sum(mjs_process_memory{type=\"total\", instance=~\"$jobmanager\"})",
       "legendFormat": "total"
      },
      {
       "expr": "sum(mjs_process_memory{type=\"used\", instance=~\"$jobmanager\"})",
       "legendFormat": "used"
      }
     ]
    },
    {
     "title": "Status",
     "type": "status-history",
     "description": "Over period [${__from:date:YYYY-MM-DD HH:mm:ss} to ${__to:date:YYYY-MM-DD HH:mm:ss}]",
     "gridPos": { "h": 4, "w": 9, "x": 0, "y": 100 },
     "targets": [
      {
       "expr": "sum(mjs_up{instance=~\"$jobmanager\"}) or 0 * sum(last_over_time(mjs_up[999d]))",
       "legendFormat": "job manager"
      }
     ]
    },
    {
     "title": "Restarts",
     "type": "gauge",
     "description": "For period [${__from:date:YYYY-MM-DD HH:mm:ss} to ${__to:date:YYYY-MM-DD HH:mm:ss}]",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 100 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(last_over_time(mjs_up{instance=~\"$jobmanager\"}[999d])) - (sum(last_over_time(mjs_up{instance=~\"$jobmanager\"}[999d] offset $__range)) or (1 + 0 * sum(last_over_time(mjs_up{instance=~\"$jobmanager\"}[999d]))))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Job Manager Events",
     "type": "timeseries",
     "description": "Over period [${__from:date:YYYY-MM-DD HH:mm:ss} to ${__to:date:YYYY-MM-DD HH:mm:ss}]",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "((1 + 0 * sum(last_over_time(mjs_up{instance=~\"$jobmanager\"}[999d]))) - (1 + 0 * sum(last_over_time(mjs_up{instance=~\"$jobmanager\"}[999d] offset $__interval)) or 0 * sum(last_over_time(mjs_up{instance=~\"$jobmanager\"}[999d])))) and sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "start"
      },
      {
       "expr": "((sum(last_over_time(mjs_up{instance=~\"$jobmanager\"}[999d])) - 1) - ((sum(last_over_time(mjs_up{instance=~\"$jobmanager\"}[999d] offset $__interval)) - 1) or 0 * sum(last_over_time(mjs_up{instance=~\"$jobmanager\"}[999d])))) and sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "restart"
      },
      {
       "expr": "0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": " "
      }
     ]
    }
   ]
  },
  {
   "title": "Scheduler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scheduling Algorithm",
     "type": "stat",
     "description": "As of ${__to:date:YYYY-MM-DD HH:mm:ss}",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum by (value) (mjs_scheduling_algorithm{instance=~\"$jobmanager\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Auto-Resizing",
     "type": "stat",
     "description": "As of ${__to:date:YYYY-MM-DD HH:mm:ss}",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(mjs_resizable{instance=~\"$jobmanager\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": " Next (Blocked) Queue Item",
     "type": "stat",
     "description": "As of ${__to:date:YYYY-MM-DD HH:mm:ss}",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "-999 * (sum(mjs_blocked_queue_item_updating{instance=~\"$jobmanager\"}) == 1)",
       "legendFormat": "__auto"
      },
      {
       "expr": "(sum by (user) (mjs_blocked_queue_item_user{instance=~\"$jobmanager\"}) == 1)",
       "legendFormat": "user"
      },
      {
       "expr": "(sum(mjs_blocked_queue_item_requirements{instance=~\"$jobmanager\",info=\"min_workers\"}) or -1 * sum(mjs_up{instance=~\"$jobmanager\"})) and sum(mjs_blocked_queue_item_updating{instance=~\"$jobmanager\"}) == 0",
       "legendFormat": "min"
      },
      {
       "expr": "(sum(mjs_blocked_queue_item_requirements{instance=~\"$jobmanager\",info=\"max_workers\"}) or -1 * sum(mjs_up{instance=~\"$jobmanager\"})) and sum(mjs_blocked_queue_item_updating{instance=~\"$jobmanager\"}) == 0",
       "legendFormat": "max"
      },
      {
       "expr": "(sum(mjs_blocked_queue_item_requirements{instance=~\"$jobmanager\",info=\"same_type\"}) or -1 * sum(mjs_up{instance=~\"$jobmanager\"})) and sum(mjs_blocked_queue_item_updating{instance=~\"$jobmanager\"}) == 0",
       "legendFormat": "sameType"
      },
      {
       "expr": "0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "-1 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Workers",
     "type": "timeseries",
     "description": "Over period [${__from:date:YYYY-MM-DD HH:mm:ss} to ${__to:date:YYYY-MM-DD HH:mm:ss}]",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "# NOTE: Leave out default value of 0 so that if the cluster is non-resizable, no line is shown\nsum(mjs_workers{type=\"max\", instance=~\"$jobmanager\"})",
       "legendFormat": "maximum"
      },
      {
       "expr": "# NOTE: Leave out default value of 0 so that if the cluster is non-resizable, no line is shown\nsum(mjs_workers{type=\"desired\", instance=~\"$jobmanager\"})",
       "legendFormat": "desired"
      },
      {
       "expr": "((sum(mjs_worker_state_transitions_total{instance=~\"$jobmanager\",to=~\"busy|idle\"}) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})) - (sum(mjs_worker_state_transitions_total{instance=~\"$jobmanager\",from=~\"busy|idle\"}) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})))",
       "legendFormat": "connected"
      },
      {
       "expr": "(sum(mjs_worker_state_transitions_total{instance=~\"$jobmanager\",to=\"busy\"}) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})) - (sum(mjs_worker_state_transitions_total{instance=~\"$jobmanager\",from=\"busy\"}) or 0 * sum(mjs_up{instance=~\"$jobmanager\"}))",
       "legendFormat": "busy"
      }
     ]
    },
    {
     "title": "Queue [$user]",
     "type": "timeseries",
     "description": "Over period [${__from:date:YYYY-MM-DD HH:mm:ss} to ${__to:date:YYYY-MM-DD HH:mm:ss}]",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(mjs_queue{instance=~\"$jobmanager\",user=~\"$user\",type=\"communicating_job\"}) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "communicating_job"
      },
      {
       "expr": "sum(mjs_queue{instance=~\"$jobmanager\",user=~\"$user\",type=\"independent_task\"}) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "independent_task"
      }
     ]
    },
    {
     "title": "Scheduler",
     "type": "timeseries",
     "description": "Over period [${__from:date:YYYY-MM-DD HH:mm:ss} to ${__to:date:YYYY-MM-DD HH:mm:ss}]",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"schedule_processed\"}[$__rate_interval])) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "load"
      }
     ]
    },
    {
     "title": "Scheduling Times [$user]",
     "type": "bargauge",
     "description": "For period [${__from:date:YYYY-MM-DD HH:mm:ss} to ${__to:date:YYYY-MM-DD HH:mm:ss}]",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "targets": [
      {
       "expr": "sum by (le) (1 * mjs_scheduling_times_bucket{instance=~\"$jobmanager\"} @ ${__to:date:seconds} or 1 * last_over_time(mjs_scheduling_times_bucket{instance=~\"$jobmanager\"}[999d] @ ${__to:date:seconds})) - sum by (le) (1 * mjs_scheduling_times_bucket{instance=~\"$jobmanager\"} @ ${__from:date:seconds} or 1 * last_over_time(mjs_scheduling_times_bucket{instance=~\"$jobmanager\"}[999d] @ ${__from:date:seconds}) or 0 * last_over_time(mjs_scheduling_times_bucket{instance=~\"$jobmanager\"}[999d]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Task Dispatcher [$user]",
     "type": "timeseries",
     "description": "Over period [${__from:date:YYYY-MM-DD HH:mm:ss} to ${__to:date:YYYY-MM-DD HH:mm:ss}]",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(mjs_task_dispatches_total{instance=~\"$jobmanager\",user=~\"$user\"}[$__rate_interval])) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "load"
      }
     ]
    },
    {
     "title": "Task Dispatch Times [$user]",
     "type": "bargauge",
     "description": "For period [${__from:date:YYYY-MM-DD HH:mm:ss} to ${__to:date:YYYY-MM-DD HH:mm:ss}]",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "targets": [
      {
       "expr": "sum by (le) (1 * mjs_task_dispatch_times_bucket{instance=~\"$jobmanager\",user=~\"$user\"} @ ${__to:date:seconds} or 1 * last_over_time(mjs_task_dispatch_times_bucket{instance=~\"$jobmanager\",user=~\"$user\"}[999d] @ ${__to:date:seconds})) - sum by (le) (1 * mjs_task_dispatch_times_bucket{instance=~\"$jobmanager\",user=~\"$user\"} @ ${__from:date:seconds} or 1 * last_over_time(mjs_task_dispatch_times_bucket{instance=~\"$jobmanager\",user=~\"$user\"}[999d] @ ${__from:date:seconds}) or 0 * last_over_time(mjs_task_dispatch_times_bucket{instance=~\"$jobmanager\",user=~\"$user\"}[999d]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Scheduler Events",
     "type": "timeseries",
     "description": "Over period [${__from:date:YYYY-MM-DD HH:mm:ss} to ${__to:date:YYYY-MM-DD HH:mm:ss}]",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum((1 * mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"worker_added\"} or 0 * mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"worker_added\"} offset $__interval + last_over_time(mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"worker_added\"}[999d])) - (1 * mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"worker_added\"} offset $__interval or 0 * mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"worker_added\"}) or last_over_time(mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"worker_added\"}[999d]) unless last_over_time(mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"worker_added\"}[999d] offset $__interval)) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "worker_added"
      },
      {
       "expr": "sum((1 * mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"worker_busy\"} or 0 * mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"worker_busy\"} offset $__interval + last_over_time(mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"worker_busy\"}[999d])) - (1 * mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"worker_busy\"} offset $__interval or 0 * mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"worker_busy\"}) or last_over_time(mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"worker_busy\"}[999d]) unless last_over_time(mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"worker_busy\"}[999d] offset $__interval)) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "worker_busy"
      },
      {
       "expr": "sum((1 * mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"worker_idle\"} or 0 * mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"worker_idle\"} offset $__interval + last_over_time(mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"worker_idle\"}[999d])) - (1 * mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"worker_idle\"} offset $__interval or 0 * mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"worker_idle\"}) or last_over_time(mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"worker_idle\"}[999d]) unless last_over_time(mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"worker_idle\"}[999d] offset $__interval)) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "worker_idle"
      },
      {
       "expr": "sum((1 * mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"worker_removed\"} or 0 * mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"worker_removed\"} offset $__interval + last_over_time(mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"worker_removed\"}[999d])) - (1 * mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"worker_removed\"} offset $__interval or 0 * mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"worker_removed\"}) or last_over_time(mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"worker_removed\"}[999d]) unless last_over_time(mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"worker_removed\"}[999d] offset $__interval)) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "worker_removed"
      },
      {
       "expr": "sum((1 * mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"item_queued\"} or 0 * mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"item_queued\"} offset $__interval + last_over_time(mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"item_queued\"}[999d])) - (1 * mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"item_queued\"} offset $__interval or 0 * mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"item_queued\"}) or last_over_time(mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"item_queued\"}[999d]) unless last_over_time(mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"item_queued\"}[999d] offset $__interval)) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "item_queued"
      },
      {
       "expr": "sum((1 * mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"item_dequeued\"} or 0 * mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"item_dequeued\"} offset $__interval + last_over_time(mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"item_dequeued\"}[999d])) - (1 * mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"item_dequeued\"} offset $__interval or 0 * mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"item_dequeued\"}) or last_over_time(mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"item_dequeued\"}[999d]) unless last_over_time(mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"item_dequeued\"}[999d] offset $__interval)) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "item_dequeued"
      },
      {
       "expr": "sum((1 * mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"job_promoted\"} or 0 * mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"job_promoted\"} offset $__interval + last_over_time(mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"job_promoted\"}[999d])) - (1 * mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"job_promoted\"} offset $__interval or 0 * mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"job_promoted\"}) or last_over_time(mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"job_promoted\"}[999d]) unless last_over_time(mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"job_promoted\"}[999d] offset $__interval)) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "job_promoted"
      },
      {
       "expr": "sum((1 * mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"job_demoted\"} or 0 * mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"job_demoted\"} offset $__interval + last_over_time(mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"job_demoted\"}[999d])) - (1 * mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"job_demoted\"} offset $__interval or 0 * mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"job_demoted\"}) or last_over_time(mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"job_demoted\"}[999d]) unless last_over_time(mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"job_demoted\"}[999d] offset $__interval)) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "job_demoted"
      },
      {
       "expr": "sum((1 * mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"schedule_processed\"} or 0 * mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"schedule_processed\"} offset $__interval + last_over_time(mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"schedule_processed\"}[999d])) - (1 * mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"schedule_processed\"} offset $__interval or 0 * mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"schedule_processed\"}) or last_over_time(mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"schedule_processed\"}[999d]) unless last_over_time(mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"schedule_processed\"}[999d] offset $__interval)) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "schedule_processed"
      },
      {
       "expr": "sum((1 * mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"scheduler_paused\"} or 0 * mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"scheduler_paused\"} offset $__interval + last_over_time(mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"scheduler_paused\"}[999d])) - (1 * mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"scheduler_paused\"} offset $__interval or 0 * mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"scheduler_paused\"}) or last_over_time(mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"scheduler_paused\"}[999d]) unless last_over_time(mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"scheduler_paused\"}[999d] offset $__interval)) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "scheduler_paused"
      },
      {
       "expr": "sum((1 * mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"scheduler_resumed\"} or 0 * mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"scheduler_resumed\"} offset $__interval + last_over_time(mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"scheduler_resumed\"}[999d])) - (1 * mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"scheduler_resumed\"} offset $__interval or 0 * mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"scheduler_resumed\"}) or last_over_time(mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"scheduler_resumed\"}[999d]) unless last_over_time(mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"scheduler_resumed\"}[999d] offset $__interval)) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "scheduler_resumed"
      },
      {
       "expr": "sum((1 * mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"task_dispatched\"} or 0 * mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"task_dispatched\"} offset $__interval + last_over_time(mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"task_dispatched\"}[999d])) - (1 * mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"task_dispatched\"} offset $__interval or 0 * mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"task_dispatched\"}) or last_over_time(mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"task_dispatched\"}[999d]) unless last_over_time(mjs_scheduler_events_total{instance=~\"$jobmanager\",type=\"task_dispatched\"}[999d] offset $__interval)) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "task_dispatched"
      },
      {
       "expr": "0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "Scheduler Errors",
     "type": "timeseries",
     "description": "Over period [${__from:date:YYYY-MM-DD HH:mm:ss} to ${__to:date:YYYY-MM-DD HH:mm:ss}]",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (type) ((1 * mjs_scheduler_errors_total{instance=~\"$jobmanager\"} or 0 * mjs_scheduler_errors_total{instance=~\"$jobmanager\"} offset $__interval + last_over_time(mjs_scheduler_errors_total{instance=~\"$jobmanager\"}[999d])) - (1 * mjs_scheduler_errors_total{instance=~\"$jobmanager\"} offset $__interval or 0 * mjs_scheduler_errors_total{instance=~\"$jobmanager\"}) or last_over_time(mjs_scheduler_errors_total{instance=~\"$jobmanager\"}[999d]) unless last_over_time(mjs_scheduler_errors_total{instance=~\"$jobmanager\"}[999d] offset $__interval))",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": " "
      }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Space",
     "type": "timeseries",
     "description": "Over period [${__from:date:YYYY-MM-DD HH:mm:ss} to ${__to:date:YYYY-MM-DD HH:mm:ss}]",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(mjs_storage{instance=~\"$jobmanager\",type=\"database\"}) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "database"
      },
      {
       "expr": "sum(mjs_storage{instance=~\"$jobmanager\",type=\"large_object_files\"}) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "large_object_files"
      },
      {
       "expr": "sum(mjs_storage{instance=~\"$jobmanager\",type=\"job_history\"}) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "job_history"
      },
      {
       "expr": "sum(mjs_storage{instance=~\"$jobmanager\",type=\"logs\"}) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "logs"
      },
      {
       "expr": "sum (mjs_storage{instance=~\"$jobmanager\",type=\"available\"})",
       "legendFormat": "available"
      }
     ]
    },
    {
     "title": "Job and Task Data [$user]",
     "type": "timeseries",
     "description": "Over period [${__from:date:YYYY-MM-DD HH:mm:ss} to ${__to:date:YYYY-MM-DD HH:mm:ss}]",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(mjs_work_unit_data{instance=~\"$jobmanager\",user=~\"$user\",type=\"job_attached_files\"}) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "job_attached_files"
      },
      {
       "expr": "sum(mjs_work_unit_data{instance=~\"$jobmanager\",user=~\"$user\",type=\"job_data\"}) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "job_data"
      },
      {
       "expr": "sum(mjs_work_unit_data{instance=~\"$jobmanager\",user=~\"$user\",type=\"job_file_value_store\"}) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "job_file_value_store"
      },
      {
       "expr": "sum(mjs_work_unit_data{instance=~\"$jobmanager\",user=~\"$user\",type=\"task_function\"}) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "task_function"
      },
      {
       "expr": "sum(mjs_work_unit_data{instance=~\"$jobmanager\",user=~\"$user\",type=\"task_input\"}) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "task_input"
      },
      {
       "expr": "sum(mjs_work_unit_data{instance=~\"$jobmanager\",user=~\"$user\",type=\"task_output\"}) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "task_output"
      },
      {
       "expr": "sum(mjs_work_unit_data{instance=~\"$jobmanager\",user=~\"$user\",type=\"task_diary\"}) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "task_diary"
      },
      {
       "expr": "sum(mjs_work_unit_data{instance=~\"$jobmanager\",user=~\"$user\",type=\"task_warnings\"}) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "task_warnings"
      },
      {
       "expr": "sum(mjs_work_unit_data{instance=~\"$jobmanager\",user=~\"$user\",type=\"other\"}) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "other"
      }
     ]
    },
    {
     "title": "Disk Activity",
     "type": "timeseries",
     "description": "Over period [${__from:date:YYYY-MM-DD HH:mm:ss} to ${__to:date:YYYY-MM-DD HH:mm:ss}]",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(rate(mjs_disk_activity_total{instance=~\"$jobmanager\",type=\"read\"}[$__rate_interval])) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "read"
      },
      {
       "expr": "sum(rate(mjs_disk_activity_total{instance=~\"$jobmanager\",type=\"write\"}[$__rate_interval])) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "write"
      },
      {
       "expr": "sum(rate(mjs_disk_activity_total{instance=~\"$jobmanager\",type=\"delete\"}[$__rate_interval])) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "delete"
      }
     ]
    },
    {
     "title": "Database Activity",
     "type": "timeseries",
     "description": "Over period [${__from:date:YYYY-MM-DD HH:mm:ss} to ${__to:date:YYYY-MM-DD HH:mm:ss}]",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(mjs_database_access_total{instance=~\"$jobmanager\"}[$__rate_interval])) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "load"
      }
     ]
    },
    {
     "title": "Database Operations",
     "type": "timeseries",
     "description": "Over period [${__from:date:YYYY-MM-DD HH:mm:ss} to ${__to:date:YYYY-MM-DD HH:mm:ss}]",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 114 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (type) ((1 * mjs_database_access_total{instance=~\"$jobmanager\"} or 0 * mjs_database_access_total{instance=~\"$jobmanager\"} offset $__interval + last_over_time(mjs_database_access_total{instance=~\"$jobmanager\"}[999d])) - (1 * mjs_database_access_total{instance=~\"$jobmanager\"} offset $__interval or 0 * mjs_database_access_total{instance=~\"$jobmanager\"}) or last_over_time(mjs_database_access_total{instance=~\"$jobmanager\"}[999d]) unless last_over_time(mjs_database_access_total{instance=~\"$jobmanager\"}[999d] offset $__interval))",
       "legendFormat": "__auto"
      },
      {
       "expr": "0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": " zero"
      }
     ]
    },
    {
     "title": "Storage Errors",
     "type": "timeseries",
     "description": "Over period [${__from:date:YYYY-MM-DD HH:mm:ss} to ${__to:date:YYYY-MM-DD HH:mm:ss}]",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 114 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (type) ((1 * mjs_storage_errors_total{instance=~\"$jobmanager\"} or 0 * mjs_storage_errors_total{instance=~\"$jobmanager\"} offset $__interval + last_over_time(mjs_storage_errors_total{instance=~\"$jobmanager\"}[999d])) - (1 * mjs_storage_errors_total{instance=~\"$jobmanager\"} offset $__interval or 0 * mjs_storage_errors_total{instance=~\"$jobmanager\"}) or last_over_time(mjs_storage_errors_total{instance=~\"$jobmanager\"}[999d]) unless last_over_time(mjs_storage_errors_total{instance=~\"$jobmanager\"}[999d] offset $__interval))",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "Cache",
     "type": "timeseries",
     "description": "Over period [${__from:date:YYYY-MM-DD HH:mm:ss} to ${__to:date:YYYY-MM-DD HH:mm:ss}]",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 122 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(mjs_work_unit_cache{instance=~\"$jobmanager\",type=\"job\"}) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "job"
      },
      {
       "expr": "sum(mjs_work_unit_cache{instance=~\"$jobmanager\",type=\"task\"}) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "task"
      }
     ]
    },
    {
     "title": "Cache Misses",
     "type": "timeseries",
     "description": "Over period [${__from:date:YYYY-MM-DD HH:mm:ss} to ${__to:date:YYYY-MM-DD HH:mm:ss}]",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 122 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(increase(mjs_work_unit_cache_queries_total{instance=~\"$jobmanager\",type=\"job\",result=\"failure\"}[$__rate_interval])) / clamp_min(sum(increase(mjs_work_unit_cache_queries_total{instance=~\"$jobmanager\",type=\"job\"}[$__rate_interval])),1) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "job"
      },
      {
       "expr": "sum(increase(mjs_work_unit_cache_queries_total{instance=~\"$jobmanager\",type=\"task\",result=\"failure\"}[$__rate_interval])) / clamp_min(sum(increase(mjs_work_unit_cache_queries_total{instance=~\"$jobmanager\",type=\"task\"}[$__rate_interval])),1) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "task"
      }
     ]
    }
   ]
  },
  {
   "title": "Communication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Data Transfer",
     "type": "timeseries",
     "description": "Over period [${__from:date:YYYY-MM-DD HH:mm:ss} to ${__to:date:YYYY-MM-DD HH:mm:ss}]",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(mjs_data_transfer_total{instance=~\"$jobmanager\",type=\"upload\"}[$__rate_interval])) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "upload"
      },
      {
       "expr": "sum(rate(mjs_data_transfer_total{instance=~\"$jobmanager\",type=\"download\"}[$__rate_interval])) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "download"
      }
     ]
    },
    {
     "title": "Network Call Activity",
     "type": "timeseries",
     "description": "Over period [${__from:date:YYYY-MM-DD HH:mm:ss} to ${__to:date:YYYY-MM-DD HH:mm:ss}]",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(mjs_network_calls_total{instance=~\"$jobmanager\",direction=\"incoming\"}[$__rate_interval])) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "incoming"
      },
      {
       "expr": "sum(rate(mjs_network_calls_total{instance=~\"$jobmanager\",direction=\"outgoing\"}[$__rate_interval])) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "outgoing"
      }
     ]
    },
    {
     "title": "Network Calls (Incoming)",
     "type": "timeseries",
     "description": "Over period [${__from:date:YYYY-MM-DD HH:mm:ss} to ${__to:date:YYYY-MM-DD HH:mm:ss}]",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (method) ((1 * mjs_network_calls_total{instance=~\"$jobmanager\",direction=\"incoming\"} or 0 * mjs_network_calls_total{instance=~\"$jobmanager\",direction=\"incoming\"} offset $__interval + last_over_time(mjs_network_calls_total{instance=~\"$jobmanager\",direction=\"incoming\"}[999d])) - (1 * mjs_network_calls_total{instance=~\"$jobmanager\",direction=\"incoming\"} offset $__interval or 0 * mjs_network_calls_total{instance=~\"$jobmanager\",direction=\"incoming\"}) or last_over_time(mjs_network_calls_total{instance=~\"$jobmanager\",direction=\"incoming\"}[999d]) unless last_over_time(mjs_network_calls_total{instance=~\"$jobmanager\",direction=\"incoming\"}[999d] offset $__interval))",
       "legendFormat": "__auto"
      },
      {
       "expr": "0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": " zero"
      }
     ]
    },
    {
     "title": "Network Calls (Outgoing)",
     "type": "timeseries",
     "description": "Over period [${__from:date:YYYY-MM-DD HH:mm:ss} to ${__to:date:YYYY-MM-DD HH:mm:ss}]",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (method) ((1 * mjs_network_calls_total{instance=~\"$jobmanager\",direction=\"outgoing\"} or 0 * mjs_network_calls_total{instance=~\"$jobmanager\",direction=\"outgoing\"} offset $__interval + last_over_time(mjs_network_calls_total{instance=~\"$jobmanager\",direction=\"outgoing\"}[999d])) - (1 * mjs_network_calls_total{instance=~\"$jobmanager\",direction=\"outgoing\"} offset $__interval or 0 * mjs_network_calls_total{instance=~\"$jobmanager\",direction=\"outgoing\"}) or last_over_time(mjs_network_calls_total{instance=~\"$jobmanager\",direction=\"outgoing\"}[999d]) unless last_over_time(mjs_network_calls_total{instance=~\"$jobmanager\",direction=\"outgoing\"}[999d] offset $__interval))",
       "legendFormat": "__auto"
      },
      {
       "expr": "0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": " zero"
      }
     ]
    },
    {
     "title": "Network Errors",
     "type": "timeseries",
     "description": "Over period [${__from:date:YYYY-MM-DD HH:mm:ss} to ${__to:date:YYYY-MM-DD HH:mm:ss}]",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (type) ((1 * mjs_network_errors_total{instance=~\"$jobmanager\"} or 0 * mjs_network_errors_total{instance=~\"$jobmanager\"} offset $__interval + last_over_time(mjs_network_errors_total{instance=~\"$jobmanager\"}[999d])) - (1 * mjs_network_errors_total{instance=~\"$jobmanager\"} offset $__interval or 0 * mjs_network_errors_total{instance=~\"$jobmanager\"}) or last_over_time(mjs_network_errors_total{instance=~\"$jobmanager\"}[999d]) unless last_over_time(mjs_network_errors_total{instance=~\"$jobmanager\"}[999d] offset $__interval))",
       "legendFormat": "{{type}}"
      },
      {
       "expr": "0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": " "
      }
     ]
    }
   ]
  },
  {
   "title": "Security",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Security Level",
     "type": "stat",
     "description": "As of ${__to:date:YYYY-MM-DD HH:mm:ss}",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 28 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(mjs_security_level{instance=~\"$jobmanager\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Admin User",
     "type": "stat",
     "description": "As of ${__to:date:YYYY-MM-DD HH:mm:ss}",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 28 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum by (user) (mjs_admin_user{instance=~\"$jobmanager\"}) == 1",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Secure Communication",
     "type": "stat",
     "description": "As of ${__to:date:YYYY-MM-DD HH:mm:ss}",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 28 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(mjs_secure_communication{instance=~\"$jobmanager\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Activity [$user]",
     "type": "timeseries",
     "description": "Over period [${__from:date:YYYY-MM-DD HH:mm:ss} to ${__to:date:YYYY-MM-DD HH:mm:ss}]",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum((1 * mjs_security_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"registration\"} or 0 * mjs_security_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"registration\"} offset $__interval + last_over_time(mjs_security_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"registration\"}[999d])) - (1 * mjs_security_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"registration\"} offset $__interval or 0 * mjs_security_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"registration\"}) or last_over_time(mjs_security_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"registration\"}[999d]) unless last_over_time(mjs_security_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"registration\"}[999d] offset $__interval)) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "registration"
      },
      {
       "expr": "sum((1 * mjs_security_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"authentication\"} or 0 * mjs_security_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"authentication\"} offset $__interval + last_over_time(mjs_security_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"authentication\"}[999d])) - (1 * mjs_security_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"authentication\"} offset $__interval or 0 * mjs_security_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"authentication\"}) or last_over_time(mjs_security_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"authentication\"}[999d]) unless last_over_time(mjs_security_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"authentication\"}[999d] offset $__interval)) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "authentication"
      },
      {
       "expr": "sum((1 * mjs_security_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"ldap_authentication\"} or 0 * mjs_security_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"ldap_authentication\"} offset $__interval + last_over_time(mjs_security_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"ldap_authentication\"}[999d])) - (1 * mjs_security_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"ldap_authentication\"} offset $__interval or 0 * mjs_security_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"ldap_authentication\"}) or last_over_time(mjs_security_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"ldap_authentication\"}[999d]) unless last_over_time(mjs_security_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"ldap_authentication\"}[999d] offset $__interval)) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "ldap_authentication"
      },
      {
       "expr": "sum((1 * mjs_security_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"password_change\"} or 0 * mjs_security_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"password_change\"} offset $__interval + last_over_time(mjs_security_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"password_change\"}[999d])) - (1 * mjs_security_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"password_change\"} offset $__interval or 0 * mjs_security_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"password_change\"}) or last_over_time(mjs_security_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"password_change\"}[999d]) unless last_over_time(mjs_security_events_total{instance=~\"$jobmanager\",user=~\"$user\",type=\"password_change\"}[999d] offset $__interval)) or 0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": "password_change"
      },
      {
       "expr": "0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "Require Client Certificate",
     "type": "stat",
     "description": "As of ${__to:date:YYYY-MM-DD HH:mm:ss}",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 32 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(mjs_require_client_certificate{instance=~\"$jobmanager\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "LDAP Server Authentication",
     "type": "stat",
     "description": "As of ${__to:date:YYYY-MM-DD HH:mm:ss}",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 32 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(mjs_ldap_server_authentication{instance=~\"$jobmanager\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Registered Users",
     "type": "stat",
     "description": "As of ${__to:date:YYYY-MM-DD HH:mm:ss}",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 32 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(mjs_users{instance=~\"$jobmanager\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Authentication Failures [$user]",
     "type": "timeseries",
     "description": "Over period [${__from:date:YYYY-MM-DD HH:mm:ss} to ${__to:date:YYYY-MM-DD HH:mm:ss}]",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (user) ((1 * mjs_authentication_failures_total{instance=~\"$jobmanager\",user=~\"$user\",type=~\"authentication|ldap_authentication\"} or 0 * mjs_authentication_failures_total{instance=~\"$jobmanager\",user=~\"$user\",type=~\"authentication|ldap_authentication\"} offset $__interval + last_over_time(mjs_authentication_failures_total{instance=~\"$jobmanager\",user=~\"$user\",type=~\"authentication|ldap_authentication\"}[999d])) - (1 * mjs_authentication_failures_total{instance=~\"$jobmanager\",user=~\"$user\",type=~\"authentication|ldap_authentication\"} offset $__interval or 0 * mjs_authentication_failures_total{instance=~\"$jobmanager\",user=~\"$user\",type=~\"authentication|ldap_authentication\"}) or last_over_time(mjs_authentication_failures_total{instance=~\"$jobmanager\",user=~\"$user\",type=~\"authentication|ldap_authentication\"}[999d]) unless last_over_time(mjs_authentication_failures_total{instance=~\"$jobmanager\",user=~\"$user\",type=~\"authentication|ldap_authentication\"}[999d] offset $__interval)) or 0 * sum by (user) (mjs_users{instance=~\"$jobmanager\"})",
       "legendFormat": "{{user}}"
      },
      {
       "expr": "0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "Authorization Failures [$user]",
     "type": "timeseries",
     "description": "Over period [${__from:date:YYYY-MM-DD HH:mm:ss} to ${__to:date:YYYY-MM-DD HH:mm:ss}]",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (user) ((1 * mjs_authorization_failures{instance=~\"$jobmanager\",user=~\"$user\",type=\"registration\"} or 0 * mjs_authorization_failures{instance=~\"$jobmanager\",user=~\"$user\",type=\"registration\"} offset $__interval + last_over_time(mjs_authorization_failures{instance=~\"$jobmanager\",user=~\"$user\",type=\"registration\"}[999d])) - (1 * mjs_authorization_failures{instance=~\"$jobmanager\",user=~\"$user\",type=\"registration\"} offset $__interval or 0 * mjs_authorization_failures{instance=~\"$jobmanager\",user=~\"$user\",type=\"registration\"}) or last_over_time(mjs_authorization_failures{instance=~\"$jobmanager\",user=~\"$user\",type=\"registration\"}[999d]) unless last_over_time(mjs_authorization_failures{instance=~\"$jobmanager\",user=~\"$user\",type=\"registration\"}[999d] offset $__interval)) or 0 * sum by (user) (mjs_users{instance=~\"$jobmanager\"})",
       "legendFormat": "{{user}}"
      },
      {
       "expr": "0 * sum(mjs_up{instance=~\"$jobmanager\"})",
       "legendFormat": " "
      }
     ]
    }
   ]
  }
 ]
}